### ISSUE TITLE
Output is always "No fucks given"

### ISSUE THREAD

**Issue by mrickard** [nvbn/thefuck#2]
Default install on OS X with pip doesn't seem to do anything other than return "No fucks given," even with example rules imported.  This might not be a code issue--there might be additional setup missing from the documentation.

**Comment by academo** [comment]
same here osx  "No fucks given," is always the output

**Comment by academo** [comment]
to expand information

```
~$ fuck rules
No fuck given rules
```

**Comment by nvbn** [comment]
Can you post output of `thefuck git brnch`?

**Comment by feliperezende** [comment]
➜  ~  thefuck git brnch
git branch
git branch
➜  ~

**Comment by mateuszbuda** [comment]
Do you know what is the path to `command_not_found` binary on osx?
And what does the `~/.rules` file contain on linux?
I guess setting command_not_found and creating correct rules file may help.

**Comment by cdipaolo** [comment]
having this same issue with pretty much anything that isn't exactly from the example on the front. Doing a git example similar to the front page `git branch` example gives:

```bash
∴ ~ git statu
git: 'statu' is not a git command. See 'git --help'.

Did you mean one of these?
	status
	stage
	stash
∴ ~ fuck
No fuck given
```

**Comment by mrickard** [comment]
▶  thefuck git brnch                                                                                                                          
    git branch
However, having aliased `fuck`, I get this: 
    ▶  fuck git brnch
    No fuck given git brnch

**Comment by Zhomart** [comment]
I just installed on OSX using `$ pip install thefuck`. Then added `alias fuck='$(thefuck $(fc -ln -1))'` to ~/.bash_profile.

```
$ vom
bash: vom: command not found
$ fuck
No fuck given

$ fuck rules
No fuck given rules
$ fuck rules
Can't fuck twice rules

$ thefuck git brnch
echo No fuck given
```

**Comment by seanhamlin** [comment]
Same here, I assume this is because the previous command is not making it into the command

```
$ alias fuck
alias fuck='$(thefuck $(fc -ln -1))'
~
$ fc -ln -1
~
$
```

**Comment by academo** [comment]
I think the problem with this is about this rule

https://github.com/nvbn/thefuck/blob/master/thefuck/rules/no_command.py

The osx terminal doesn't return suggestion (at least not mine) about possible commands and that is why it can not find a command to execute.

Example osx:

```
~$ puthon
bash: puthon: command not found
```

vs linux:
```
~$ puthon
No command 'puthon' found, did you mean:
 Command 'python' from package 'python-minimal' (main)
 Command 'python' from package 'python3' (main)
zsh: command not found: puthon
```

**Comment by grammakov** [comment]
same issue:

```
➜  ~  git st           
git: 'st' is not a git command. See 'git --help'.

Did you mean one of these?
	status
	reset
	stage
	stash
	svn
➜  ~  fuck
No fuck given
```
```
➜  ~  fuck rules
Can't fuck twice rules
```

**Comment by okonet** [comment]
+1. I'm using zsh on OS X 10.10.3

```
» g brnch
git: 'brnch' is not a git command. See 'git --help'.

Did you mean this?
	branch
--- adverity/web-app ‹develop*M› » fuck                                                                                                                   1 ↵
No fuck given
» fuck rules
Can't fuck twice rules
» alias fuck
fuck='$(thefuck $(fc -ln -1))'
```

**Comment by nvbn** [comment]
@grammakov, @okonet is it works on 1.14+?

**Comment by ignatov** [comment]
@nvbn Works good for me, Mac OS X 10.10, zsh. Thanks.

**Comment by mrickard** [comment]
Yep, good here with pip install on OS X 10.10.

**Comment by cdipaolo** [comment]
Yeah confirming it works now on OS X 10.10

**Comment by kilojoules** [comment]
On 10.10 thefuck didn't immediately work after `brew install thefuck`. Is there something I ned to do for proper configuration?

    $ puthon
    -bash: puthon: command not found
    $ thefuck
    No fuck given
    $

**Comment by scorphus** [comment]
@kilojoules `thefuck` is the binary that reads the last command from the shell history, tries to correct it and, if so, gives it back to the shell to be ran again. This interaction has to be done by way of an `alias` (or `function` in some cases – Fish Shell for instance). You should declare your alias as the README states.

**Comment by scorphus** [comment]
Also, `brew` told you that too:
```
» brew install thefuck
[snip]
==> Caveats
Add the following to your .bash_profile, .bashrc or .zshrc:
  bash: eval "$(thefuck-alias)"

  Other shells: https://github.com/nvbn/thefuck/wiki/Shell-aliases
[snip]
```

**Comment by kilojoules** [comment]
Can you clarrify these instructions? When I add `bash: eval
"$(thefuck-alias)"` I get -bash: bash:: command not found. When I add `eval
"$(thefuck-alias)"` I get `No Fucks Given`...

Best,
Julian

**Comment by scorphus** [comment]
Og! Certainly, that message can be improved, I'll do so, thank you for that!

The line you should add to your `.bashrc` is:

`eval "$(thefuck-alias)"`

**Comment by scorphus** [comment]
Done so :arrow_up: :wink:

**Comment by jordelver** [comment]
I'm having this problem still :(

I installed with `brew install thefuck`

If I try the example
```shell
~ $ thefuck git brnch
No fucks given
```

I followed the instructions to add fish function and that gives the same output.

```shell
$ fish -v
fish, version 2.1.2

~ $ thefuck -v
The Fuck 2.7
```

Any ideas what's wrong?

**Comment by scorphus** [comment]
I'm experiencing the same but only for specific commands. I'm hunting it
and will keep this updated.
Em 13/08/2015 12:03, "Jordan Elver" <notifications@github.com> escreveu:

**Comment by jordelver** [comment]
Great, thanks :+1:

**Comment by scorphus** [comment]
@jordelver what's the output of `thefuck git brnch` if you declare `debug = True` in your `~/.thefuck/settings.py`?

**Comment by jordelver** [comment]
Here you go @scorphus :)

```shell
~ $ thefuck git brnch
DEBUG: Run with settings: {'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'no_colors': True,
 'priority': {},
 'require_confirmation': True,
 'rules': [],
 'wait_command': 3}
DEBUG: Received stdout: 
DEBUG: Received stderr: 08:03:53.456375 git.c:555               trace: exec: 'git-brnch'
08:03:53.456746 run-command.c:351       trace: run_command: 'git-brnch'
git: 'brnch' is not a git command. See 'git --help'.

Did you mean this?
	branch

DEBUG: Call: fish -ic "git brnch"; with env: {'VERSIONER_PYTHON_PREFER_32_BIT': 'no', '__fish_bin_dir': '/usr/local/Cellar/fish/HEAD/bin', 'LOGNAME': 'jord', 'USER': 'jord', 'PATH': '/usr/local/Cellar/fzf/HEAD/bin:/Users/jord/.fzf/bin:/Users/jord/.rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin', 'HOME': '/Users/jord', 'DISPLAY': '/private/tmp/com.apple.launchd.cK00syPF8a/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'C', 'TERM': 'screen-256color', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.gLFdjoUbyR/Render', 'COLORFGBG': '7;0', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '2', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w0t0p0', 'XPC_SERVICE_NAME': '0', 'PYTHONPATH': '/usr/local/Cellar/thefuck/2.7/libexec/lib/python2.7/site-packages:/usr/local/Cellar/thefuck/2.7/libexec/vendor/lib/python2.7/site-packages', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.NHKCLDRw9z/Listeners', 'TMUX': '/private/var/folders/n8/j262k8b55t566gvwbdzjbz_80000gn/T/tmux-501/default,10042,0', '__fish_sysconfdir': '/usr/local/Cellar/fish/HEAD/etc/fish', 'SHELL': '/usr/local/bin/fish', 'ITERM_PROFILE': 'Default', 'LC_ALL': 'C', 'TMPDIR': '/var/folders/n8/j262k8b55t566gvwbdzjbz_80000gn/T/', '__fish_datadir': '/usr/local/Cellar/fish/HEAD/share/fish', 'GIT_TRACE': '1', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/jord', '__fish_help_dir': '/usr/local/Cellar/fish/HEAD/share/doc/fish', 'TMUX_PANE': '%1'}; took: 0:00:00.102005
DEBUG: Loaded rules: brew_install, brew_unknown_command, brew_upgrade, cargo, cargo_no_command, cd_correction, cd_mkdir, cd_parent, composer_not_command, cp_omitting_directory, cpp11, dirty_untar, dirty_unzip, django_south_ghost, django_south_merge, docker_not_command, dry, fix_alt_space, fix_file, git_add, git_branch_delete, git_branch_list, git_checkout, git_diff_staged, git_fix_stash, git_not_command, git_pull, git_pull_clone, git_push, git_push_pull, git_stash, go_run, grep_recursive, gulp_not_task, has_exists_script, heroku_not_command, history, java, javac, lein_not_task, ls_lah, man, man_no_space, mercurial, mkdir_p, no_command, no_such_file, open, pip_unknown_command, python_command, python_execute, quotation_marks, rm_dir, sed_unterminated_s, sl_ls, ssh_known_hosts, sudo, switch_lang, systemctl, test.py, tmux, tsuru_login, tsuru_not_command, whois
DEBUG: Trying rule: brew_install; took: 0:00:00.000010
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000005
DEBUG: Trying rule: brew_upgrade; took: 0:00:00.000003
DEBUG: Trying rule: cargo; took: 0:00:00.000003
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000002
DEBUG: Trying rule: cd_correction; took: 0:00:00.000005
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000006
DEBUG: Trying rule: cd_parent; took: 0:00:00.000003
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000003
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000005
DEBUG: Trying rule: cpp11; took: 0:00:00.000003
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000002
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000003
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000003
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000005
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000007
DEBUG: Trying rule: dry; took: 0:00:00.000005
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000005
DEBUG: Trying rule: fix_file; took: 0:00:00.000009
DEBUG: Trying rule: git_add; took: 0:00:00.000004
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000003
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000004
DEBUG: Trying rule: git_checkout; took: 0:00:00.000004
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000003
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000003
DEBUG: Trying rule: git_not_command; took: 0:00:00.000003
DEBUG: Trying rule: git_pull; took: 0:00:00.000003
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000003
DEBUG: Trying rule: git_push; took: 0:00:00.000003
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000003
DEBUG: Trying rule: git_stash; took: 0:00:00.000003
DEBUG: Trying rule: go_run; took: 0:00:00.000003
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000003
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000005
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000027
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000007
DEBUG: Trying rule: history; took: 0:00:00.076158
DEBUG: Trying rule: java; took: 0:00:00.000021
DEBUG: Trying rule: javac; took: 0:00:00.000004
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000006
DEBUG: Trying rule: ls_lah; took: 0:00:00.000007
DEBUG: Trying rule: man; took: 0:00:00.000008
DEBUG: Trying rule: man_no_space; took: 0:00:00.000006
DEBUG: Trying rule: mercurial; took: 0:00:00.000009
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000005
DEBUG: Trying rule: no_command; took: 0:00:00.000010
DEBUG: Trying rule: no_such_file; took: 0:00:00.000846
DEBUG: Trying rule: open; took: 0:00:00.000005
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000007
DEBUG: Trying rule: python_command; took: 0:00:00.000011
DEBUG: Trying rule: python_execute; took: 0:00:00.000009
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000008
DEBUG: Trying rule: rm_dir; took: 0:00:00.000008
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000005
DEBUG: Trying rule: sl_ls; took: 0:00:00.000007
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000010
DEBUG: Trying rule: sudo; took: 0:00:00.000052
DEBUG: Trying rule: switch_lang; took: 0:00:00.000004
DEBUG: Trying rule: systemctl; took: 0:00:00.000006
DEBUG: Trying rule: test.py; took: 0:00:00.000070
DEBUG: Trying rule: tmux; took: 0:00:00.000007
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000006
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000003
DEBUG: Trying rule: whois; took: 0:00:00.000003
DEBUG: Matched rules: 
No fucks given
DEBUG: Total took: 0:00:00.317003
```

**Comment by scorphus** [comment]
Hello, @jordelver! Yesterday I found some spare time to try and improve the `fuck.fish` function. This is how it looks now:
```fish
function fuck -d 'Correct your previous console command'
    set -l exit_code $status
    set -x TF_ALIAS fuck
    set -l fucked_up_command $history[1]
    thefuck $fucked_up_command | read unfucked_command
    if [ "$unfucked_command" != "" ]
        eval $unfucked_command
        if test $exit_code -ne 0
            history --delete $fucked_up_command
            history --merge
            return 0
        end
    end
end
```
Can you please test it and tell me how it behaves? It's way faster now :smiley: 

Thanks!

**Comment by jordelver** [comment]
Hey @scorphus. I'm confused, the example above doesn't use the fish function does it? Doesn't it invoke the `thefuck` command directly? I'm happy to test this out though :)

**Comment by scorphus** [comment]
Hello, @jordelver! That example **is** – *or will be* – the Fish function! :smiley: Right on line 5 it calls TheFuck directly – `thefuck $fucked_up_command | read unfucked_command `

This is my attempt to improve the alias for TheFuck on Fish Shell. And I believe it's way faster, as it doesn't deal with file creating/writing/reading/deleting.

Thanks for taking the time to test it! :+1:

**Comment by scorphus** [comment]
@jordelver: ping

**Comment by scorphus** [comment]
Can anyone give that function a try?

**Comment by jordelver** [comment]
Sorry for the delay. I've tried it out but I get the same output as before :(

If `thefuck git brnch` doesn't work, I don't understand why this would? I don't understand :(

**Comment by scorphus** [comment]
Really, we should go back to the root of the problem.

**Comment by scorphus** [comment]
So let's try and do so:

 * What OS are you on?
 * What's the output of all the following commands?

```bash
$ pip freeze
```

```bash
$ python -c 'import sys; print(sys.version)'
```

```bash
$ which python
```

```bash
$ ls - lha $(dirname $(dirname $(which python)))/lib/py*/site-packages/
```

```bash
$ python -c 'import psutil; print(psutil); print(psutil.__version__);'
```

Thanks!

**Comment by jordelver** [comment]
Thanks. I'm on Mac OS X 10.10.4.

```
$ pip freeze
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
doge==3.5.0
vboxapi==1.0
wheel==0.24.0
```

```
$ python -c 'import sys; print(sys.version)'
2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
```

```
$ which python
/usr/local/bin/python
```

```
$ ls - lha $(dirname $(dirname $(which python)))/lib/py*/site-packages/
ls: -: No such file or directory
ls: lha: No such file or directory
/usr/local/lib/python2.7/site-packages/:
_markerlib				 pkg_resources
doge					setuptools
doge-3.5.0.dist-info			setuptools-18.0.1-py2.7.egg-info
easy_install.py				sitecustomize.py
easy_install.pyc			sitecustomize.pyc
pip					        wheel
pip-7.1.0-py2.7.egg-info		wheel-0.24.0-py2.7.egg-info

/usr/local/lib/python3.4/site-packages/:
__pycache__			pip-7.1.0-py3.4.egg-info	sitecustomize.py
_markerlib			pkg_resources			wheel
easy_install.py			setuptools			wheel-0.24.0-py3.4.egg-info
pip				        setuptools-18.1-py3.4.egg-info
```

```
$ python -c 'import psutil; print(psutil); print(psutil.__version__);'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named psutil
```

**Comment by scorphus** [comment]
Sorry, I'm so used giving support to Linux users... How did you install TheFuck?

Please paste the output of:

```bash
ls /usr/local/Cellar/thefuck/*/libexec/vendor/lib/python2.7/site-packages/
```

**Comment by jordelver** [comment]
Fish shell didn't like your wildcard so I did this :)

```
$ ls -1 /usr/local/Cellar/thefuck/2.7/libexec/vendor/lib/python2.7/site-packages/
_markerlib
_psutil_osx.so
_psutil_posix.so
colorama
colorama-0.3.3-py2.7.egg-info
easy_install.py
pathlib-1.0.1-py2.7.egg-info
pathlib.py
pathlib.pyc
pkg_resources
psutil
psutil-2.2.1-py2.7.egg-info
setuptools
setuptools-18.0.1-py2.7.egg-info
six-1.9.0-py2.7.egg-info
six.py
six.pyc
```

**Comment by scorphus** [comment]
@jordelver: Sorry for delay, I've had an intense day.

  1. What does `$ ls -lhart (which thefuck)` tell you?
  2. Also, do other unfucks work? Such as:
    1. `$ thefuck echoo ok`
    2. `$ thefuck cd non-existing-dir`
    3. `$thefuck brew intall`
  3. Would you try upgrading Fish and TheFuck? A.k.a.:

        $ brew update
        $ brew upgrade fish thefuck  # please copy and paste output of this one

Thanks!

**Comment by scorphus** [comment]
@jordelver: ping :smile:

**Comment by jschank** [comment]
I had this problem too, and for me the problem was that I had installed fish, with homebrew, and used the --HEAD option. Apparently when you do this, updating/upgrading doesn't work. For me I had to uninstall fish, and then reinstall it to get to the latest. (at the time that was fish 2.2.0) And that solved it for me.

Others may benefit from checking this
