### ISSUE TITLE
No longer works with an alias to “git push”

### ISSUE THREAD

**Issue by ProgVal** [nvbn/thefuck#549]
Hi,

I recently installed a new system, but kept my old oh-my-zsh aliases.
Before, I could type `gp` (alias for `git push`), and use thefuck to do the `gp --set-upstream origin branchname` for me. However, now the suggestion is `gyp`:

```
 dev-ipfs@particle  ~/rust-multiaddr   fix-protocol-codes  gp
fatal: The current branch fix-protocol-codes has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin fix-protocol-codes

 ✘ dev-ipfs@particle  ~/rust-multiaddr   fix-protocol-codes  f
gyp [enter/↑/↓/ctrl+c]
```

**Comment by SimenB** [comment]
@ProgVal for that case in particular you can do `gpsup`

**Comment by darrynten** [comment]
👍

**Comment by ahrenstein** [comment]
+1

**Comment by nvbn** [comment]
Probably fixed in 3.17.

**Comment by shssoichiro** [comment]
This does not seem to be fixed in 3.17

**Comment by Shir0kamii** [comment]
I confirm this is not fixed, I'm in 3.18 and this is still present.

**Comment by scorphus** [comment]
What do you get from the following command?

```shell
TF_ALIAS=alias TF_SHELL_ALIASES=$(alias) PYTHONIOENCODING=utf-8 thefuck gp
```

**Comment by edwardsmit** [comment]
@scorphus `No fucks given`

The alias gp is set to `git push`

**Comment by scorphus** [comment]
Oh, sorry, I forgot to mention: make sure to run it from a Git repository with commits to be pushed. INW, run it in a scenario where it would correct a previous `gp`.

**Comment by edwardsmit** [comment]
@scorphus 🎉 You're on to something, because now it correctly generates the command I expect: `git push --set-upstream origin feature/test [enter/↑/↓/ctrl+c]`

**Comment by scorphus** [comment]
Great! So, what happens if, instead of that command I posted [earlier](https://github.com/nvbn/thefuck/issues/549#issuecomment-324077979), you run `fuck`? It _should_ generate the same. Does it?

If it does: YAY! 🎉 

If it doesn't: there might be something wrong with the way your `fuck` alias/function gets declared/interpreted/generated/whatever.

Waiting on you ;-)

**Comment by edwardsmit** [comment]
Unfortunately it doesn't. I verified that TheFuck is initialised **after** the alias is defined like so:
```
echo $(alias)
# TheFuck
eval "$(thefuck --alias)"
```
Which showed me that the aliases are defined before the first call to `thefuck`

**Comment by gligoran** [comment]
I'm having a similar issue:

```
$ ~/repo git:(my-branch) gp
fatal: The current branch my-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin my-branch

$ ~/repo git:(my-branch) fuck
No fucks given
$ ~/repo git:(my-branch) git push
fatal: The current branch my-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin my-branch

$ ~/repo git:(my-branch) fuck
git push --set-upstream origin my-branch [enter/↑/↓/ctrl+c]
```

I'm using Oh My Zsh with the git plugin. As you can see if I type out the git command, it works as it should, but it doesn't give a fuck for my alias.

I'm running this on a Ubuntu 14.04 that's running through vagrant.

**Comment by edwardsmit** [comment]
@scorphus Is there anything I can do to help you debug/fix this problem?

**Comment by scorphus** [comment]
@edwardsmit: the problem seems to be not with TehFuck itself but rather with the `fuck` function on your environment. You see, it works when you [run `thefuck` manually](https://github.com/nvbn/thefuck/issues/549#issuecomment-324243535). Let's try and identify where the problem might be. It may be a daunting process, so please bear with me. What are the outputs of the following two commands:

- `type fuck`
- `functions fuck`

**Comment by edwardsmit** [comment]
@scorphus 
```
type fuck
fuck is a shell function from /Users/edwardsmit/.zshrc
fuck is /usr/local/bin/fuck

functions fuck
fuck () {
        TF_PREVIOUS=$(fc -ln -1 | tail -n 1)
        TF_CMD=$(
                    TF_ALIAS=fuck
                    TF_SHELL_ALIASES=$(alias)
                    PYTHONIOENCODING=utf-8
                    thefuck $TF_PREVIOUS THEFUCK_ARGUMENT_PLACEHOLDER $*
                )  && eval $TF_CMD
        test -n "$TF_CMD" && print -s $TF_CMD
}
```

**Comment by edwardsmit** [comment]
@scorphus Is there anything I can help you with at this point?

**Comment by edwardsmit** [comment]
ping @scorphus

**Comment by edwardsmit** [comment]
Just tried out today, and seems fixed with 3.25
AFAIC this issue can be closed

**Comment by scorphus** [comment]
Hey @edwardsmit,

Glad it's working for you again! Thanks for keep us posted.

Somehow I missed your replies, I'm really sorry about that. I'll review my notification settings.

So, I will close this one for now but if any of you users still experience this issue, please just reopen it.

**Comment by hugovk** [comment]
It's not working for me (on macOS High Sierra). 

Info:

```bash
⌂66% [hugo:~/github/test] delete-me 3s 1 ± alias fuck
fuck='eval $(thefuck $(fc -ln -1)); history -r'
```
```bash
⌂69% [hugo:~/github/test] delete-me 2s ± brew info thefuck
thefuck: stable 3.25 (bottled), HEAD
Programatically correct mistyped console commands
https://github.com/nvbn/thefuck
/usr/local/Cellar/thefuck/3.25 (710 files, 6.3MB)
  Poured from bottle on 2017-12-04 at 15:32:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/thefuck.rb
==> Requirements
Required: python3 ✔
==> Caveats
Add the following to your .bash_profile, .bashrc or .zshrc:

  eval $(thefuck --alias)

For other shells, check https://github.com/nvbn/thefuck/wiki/Shell-aliases
```

Using `gp` doesn't work:

```bash
⌂66% [hugo:~/github/test] master 1 ± gco -b delete-me
Switched to a new branch 'delete-me'
```
```bash
⌂61% [hugo:~/github/test] delete-me ± alias gp
gp='git push'
```
```bash
⌂65% [hugo:~/github/test] delete-me ± gp
fatal: The current branch delete-me has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin delete-me

```
```bash
⌂65% [hugo:~/github/test] delete-me 128 ± fuck
gcp [enter/↑/↓/ctrl+c]
usage: git cherry-pick [<options>] <commit-ish>...
   or: git cherry-pick <subcommand>

    --quit                end revert or cherry-pick sequence
    --continue            resume revert or cherry-pick sequence
    --abort               cancel revert or cherry-pick sequence
    -n, --no-commit       don't automatically commit
    -e, --edit            edit the commit message
    -s, --signoff         add Signed-off-by:
    -m, --mainline <parent-number>
                          select mainline parent
    --rerere-autoupdate   update the index with reused conflict resolution if possible
    --strategy <strategy>
                          merge strategy
    -X, --strategy-option <option>
                          option for merge strategy
    -S, --gpg-sign[=<key-id>]
                          GPG sign commit
    -x                    append commit name
    --ff                  allow fast-forward
    --allow-empty         preserve initially empty commits
    --allow-empty-message
                          allow commits with empty messages
    --keep-redundant-commits
                          keep redundant, empty commits

fc: event not found: -r
```

Using `git push` works:
```bash
⌂119% [hugo:~/github/test] delete-me ± git push
fatal: The current branch delete-me has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin delete-me

```
```bash
⌂91% [hugo:~/github/test] delete-me 128 ± fuck
git push --set-upstream origin delete-me [enter/↑/↓/ctrl+c]
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/hugovk/test
 * [new branch]      delete-me -> delete-me
Branch 'delete-me' set up to track remote branch 'delete-me' from 'origin'.
fc: event not found: -r
```

**Comment by hugovk** [comment]
@scorphus Thanks, that fixed it!

You were right, I had an old `alias fuck='eval $(thefuck $(fc -ln -1)); history -r'` in my .zshrc, replacing that with `eval $(thefuck --alias)` gives this:
```bash
94% [hugo:~] 1 % which fuck
fuck () {
	TF_PREVIOUS=$(fc -ln -1 | tail -n 1)
	TF_CMD=$( TF_ALIAS=fuck TF_SHELL_ALIASES=$(alias) PYTHONIOENCODING=utf-8 thefuck $TF_PREVIOUS THEFUCK_ARGUMENT_PLACEHOLDER $* )  && eval $TF_CMD
	test -n "$TF_CMD" && print -s $TF_CMD
}
```
```bash
⌂71% [hugo:~/github/test] delete-me3 ± gp
fatal: The current branch delete-me3 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin delete-me3

```
```bash
⌂71% [hugo:~/github/test] delete-me3 128 ± fuck
git push --set-upstream origin delete-me3 [enter/↑/↓/ctrl+c]
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/hugovk/test
 * [new branch]      delete-me3 -> delete-me3
Branch 'delete-me3' set up to track remote branch 'delete-me3' from 'origin'.
```

**Comment by Jean85** [comment]
I'm currently having this issue using the OhMyZsh plugin. I have just installed my machine, so it's all perfectly clean.

The plugin seems to be in order: https://github.com/robbyrussell/oh-my-zsh/blob/ebda8af870acc295388ed187f0139a8bffa83196/plugins/thefuck/thefuck.plugin.zsh#L7

How can I debug this further?
