### ISSUE TITLE
Execting fuck prints thefuck usage 

### ISSUE THREAD

**Issue by agross** [nvbn/thefuck#725]
```sh
$ zsh --version
zsh 5.4.2 (x86_64-apple-darwin16.7.0)

agross@firiel ~
$ thefuck --version
The Fuck 3.24 using Python 3.6.3

agross@firiel ~
$ git stat
git: 'stat' is not a git command. See 'git --help'.

The most similar commands are
	status
	stage
	stash

agross@firiel ~
$ fuck
usage: thefuck [-v] [-a [ALIAS]] [-l SHELL_LOGGER]
               [--enable-experimental-instant-mode] [-h] [-y | -r] [-d]
               [command [command ...]]

agross@firiel ~
$ whence -f fuck
fuck () {
	TF_HISTORY=$(fc -ln -10)
	TF_CMD=$(
                    TF_ALIAS=fuck
                    TF_SHELL_ALIASES=$(alias)
                    TF_HISTORY=$TF_HISTORY
                    PYTHONIOENCODING=utf-8
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $*
                )  && eval $TF_CMD
	test -n "$TF_CMD" && print -s $TF_CMD
}

agross@firiel ~
$ setopt
alwaystoend
autocd
noautoparamslash
autopushd
nobgnice
completeinword
correct
correctall
extendedhistory
globdots
histexpiredupsfirst
histignoredups
histreduceblanks
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
menucomplete
monitor
nonotify
promptsubst
pushdignoredups
recexact
rmstarwait
sharehistory
shinstdin
zle
```

**Comment by cojack** [comment]
```
╭─cojack@cojack-laptop ~ ‹v8.5.0› 
╰─$ git bara                                                                                                                                                                                                                                                         20:45:22
git: 'bara' is not a git command. See 'git --help'.

The most similar command is
        branch
╭─cojack@cojack-laptop ~ ‹v8.5.0› 
╰─[1 ↵]─$ fuck                                                                                                                                                                                                                                                       20:45:25
[WARN] Script not found in output log
No fucks given
```
still doesn't work

**Comment by agross** [comment]
@cojack What do you mean by it "still" doesn't work?

**Comment by akuma** [comment]
+1

**Comment by ianmurrays** [comment]
Same behavior here, it happened to me after upgrading thefuck to the latest version. Unfortunately I'm not sure what my previous version was.

**Comment by agross** [comment]
Closing because #733 was merged. Just found out by accident this was fixed in 3.25.

**Comment by Walsonde** [comment]
This issue is marked as closed while the problem still exists. All thefuck ever does is printing "usage: thefuck…".
